### ISSUE TITLE
ngchm error about java

### ISSUE THREAD

**Issue by Rui-Jing** [broadinstitute/infercnv#386]
Hi, team:
             Thanks for developing this user-friendly tools . Recently ,I want to use **Next Generation Clustered Heat Map** to visualise my heatmap data. But it occured an error when i runing the code: 
**p11_cnv <- readRDS(file = './infercnv_p11/preliminary.infercnv_obj')**

**library(NGCHM)
ngchm(infercnv_obj = p11_cnv,
      out_dir = "./infercnv_p11/",
      path_to_shaidyMapGen = './infercnv_p11/ShaidyMapGen.jar')**

The **error** is :
START Data Generator Heat Map Generation: Tue Dec 28 09:59:45 CST 2021
**No protocol specified
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.**
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
	at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.buildTnThumbnail(Unknown Source)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
	at mda.ngchm.datagenerator.ShaidyRMapGen.main(Unknown Source)
**Error in NGCHM::chmExportToFile(hm, file_path, overwrite = TRUE, shaidyMapGen = path_to_shaidyMapGen) : 
  export to ngchm failed**

**My packages version:**
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

NGCHM    0.12.6
infercnvNGCHM   0.1.1
infercnv  1.10.1
**java version:**
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

In addition, I tried **xhost +** for soving this error,but failed.
 
Another question is what **gene_symbol** in ngchm i can select, my sample species is mouse.

I sincerely hope to get your kind help, thanks.

**Comment by GeorgescuC** [comment]
Hi @Rui-Jing ,

Are you perhaps trying to run the NGCHM on a machine you are connected to via SSH ? From my experience, errors related to the "DISPLAY" environment variable occur when connecting via SSH without X11 forwarding ("-X" or "-Y" arguments). If you are using `screen` through an SSH connection with X11 forwarding, you may also need to check what the variable is set to outside of `screen`, and set it again inside.

Regards,
Christophe.

**Comment by jpjais** [comment]
Hi @Rui-Jing,
You can try to add the parameter **shaidyMapGenArgs = "-Djava.awt.headless=true"** in the chmExportToFile function. On my linux system, it solves the problem.
Regards,
Jean-Philippe
